// Generated by CoffeeScript 1.2.1-pre
(function() {

  define(['router'], function(Router) {
    var initialize;
    initialize = function() {
      return Router.initialize();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
