// Generated by CoffeeScript 1.2.1-pre
(function() {

  require.config({
    baseUrl: 'js/',
    paths: {
      text: 'libs/require/text',
      templates: '../templates'
    }
  });

  require(['app'], function(App) {
    return App.initialize();
  });

}).call(this);
