// Generated by CoffeeScript 1.2.1-pre
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define(['views/List'], function(ListView) {
    var AppRouter, initialize;
    AppRouter = (function(_super) {

      __extends(AppRouter, _super);

      AppRouter.name = 'AppRouter';

      function AppRouter() {
        return AppRouter.__super__.constructor.apply(this, arguments);
      }

      AppRouter.prototype.routes = {
        '*actions': 'defaultAction'
      };

      AppRouter.prototype.defaultAction = function(actions) {
        return ListView.render();
      };

      return AppRouter;

    })(Backbone.Router.extend);
    initialize = function() {
      var app_router;
      app_router = new AppRouter;
      return Backbone.history.start();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
