// Generated by CoffeeScript 1.2.1-pre
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define(['models/Item', 'api.config'], function(Item, API) {
    var List;
    return List = (function(_super) {

      __extends(List, _super);

      List.name = 'List';

      function List() {
        return List.__super__.constructor.apply(this, arguments);
      }

      List.prototype.urlRoot = API.URL;

      List.prototype.model = Item;

      return List;

    })(Backbone.Collection);
  });

}).call(this);
