// Generated by CoffeeScript 1.2.1-pre
(function() {

  describe("Item common capabilities", function() {
    var item;
    item = "";
    beforeEach(function() {
      return item = new Item({
        done: false,
        content: "Test"
      });
    });
    it("should be able to toggle from undone to done", function() {
      item.toggleDone();
      return expect(item.get('done')).toEqual(true);
    });
    it("should be able to set a new text", function() {
      item.setText("New Text");
      return expect(item.get('content')).toEqual("New Text");
    });
    return describe("when being created", function() {
      beforeEach(function() {
        return item = new Item({
          done: false,
          content: "Test"
        });
      });
      return it("should complain if it does not have a text", function() {
        item.setText("");
        return expect(item.validate()).toEqual("Item content can't be blank");
      });
    });
  });

}).call(this);
